midtrans: {}

xendit:
  ewallet:
    legacyEnabled: true
    ovo:
      invoice: false
      legacy: false
    dana:
      invoice: false
      legacy: false
    linkaja:
      invoice: false
      legacy: false
